import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import '@/app/globals.css';
import { Providers } from '@/app/providers';
import { THEME_SCRIPT } from '@/components/providers/ThemeProvider';
import { Footer } from '@/components/nav/Footer';
import { CloudflareGuard } from '@/components/common/CloudflareGuard';
import { CookieConsent } from '@/components/common/CookieConsent';
import { Analytics } from '@/components/common/Analytics';
import { OPERATOR } from '@/lib/legal';

export const metadata: Metadata = {
  /**
   * Resolves every relative URL below — canonicals, Open Graph images, the
   * sitemap reference. Without it Next emits relative og:image URLs, which
   * most scrapers refuse, so the social preview silently never appears.
   */
  metadataBase: new URL(OPERATOR.siteUrl),

  /**
   * `template` gives each route a distinct, descriptive tab and search title
   * from the short one it exports, while `default` covers routes that set
   * none. Identical titles across a site are the single most common on-page
   * SEO fault.
   */
  title: {
    default: 'FRIGAT — Provably fair casino games',
    template: '%s — FRIGAT',
  },
  description:
    'Provably fair casino games with verifiable outcomes. Every roll, drop and card is committed to a published seed hash before it is dealt, so any round can be checked after the fact.',
  applicationName: 'FRIGAT',
  alternates: { canonical: '/' },

  openGraph: {
    type: 'website',
    siteName: 'FRIGAT',
    title: 'FRIGAT — Provably fair casino games',
    description:
      'Every outcome is committed to a published seed hash before the round is dealt, so it can be verified afterwards.',
    url: '/',
    locale: 'en',
    // The image itself is generated by app/opengraph-image.tsx; Next wires it
    // in automatically, so listing it here would duplicate the tag.
  },
  twitter: {
    card: 'summary_large_image',
    title: 'FRIGAT — Provably fair casino games',
    description:
      'Every outcome is committed to a published seed hash before the round is dealt, so it can be verified afterwards.',
  },

  /**
   * The monogram ships as a transparent PNG, which is what a tab wants in
   * either theme — the previous single JPEG had an opaque background that
   * showed as a light box in the dark tab strip. `apple-touch-icon` is served
   * from the same asset: iOS composites its own rounded mask over it.
   */
  icons: {
    icon: [{ url: '/frigat-monogram.png', type: 'image/png' }],
    shortcut: [{ url: '/frigat-monogram.png', type: 'image/png' }],
    apple: [{ url: '/frigat-monogram.png' }],
  },

  /**
   * A gambling product should not be surfacing player-facing pages to
   * under-age search users through rich previews; this is the standard signal
   * that the site is adult-oriented.
   */
  other: { rating: 'adult' },

  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large' },
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  // lang/dir start out English and are rewritten by the provider once it has
  // read the stored preference — the server cannot know it before hydration.
  //
  // data-theme starts at the same default and is corrected by the inline
  // script below *before* the first paint, so a reload never flashes the dark
  // palette at someone who chose light. suppressHydrationWarning covers the
  // attribute the script writes behind React's back.
  return (
    <html lang="en" dir="ltr" data-theme="dark" className="dark" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
      </head>
      <body>
        {/* The footer sits inside the providers so its labels translate with
            the rest of the tree, and outside {children} so every route —
            dashboard, auth and admin alike — ends with the same sitemap. */}
        <Providers>
          {/* Session-scoped security check. Inside Providers so it can use the
              theme tokens, and wrapping everything so it gates the whole
              platform rather than one route. */}
          <CloudflareGuard>
            {children}
            <Footer />
            {/* Last in the tree so the banner is the final tab stop rather
                than an obstacle in front of the page, and so the analytics
                loader mounts after the content it must not delay. */}
            <CookieConsent />
            <Analytics />
          </CloudflareGuard>
        </Providers>
      </body>
    </html>
  );
}
